workflows:
  flutter-pos:
    name: Flutter POS Workflow
    max_build_duration: 60
    environment:
      android_signing:
        - pos_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.mitienda.pos"
        GOOGLE_PLAY_TRACK: "internal"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
      - name: Build Windows with Flutter
        script: |
          flutter build windows --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - build/windows/runner/Release/
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - tu-email@ejemplo.com
        notify:
          success: true
          failure: false
