workflows:
  flutter-pos:
    name: Flutter POS Workflow
    max_build_duration: 60
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.mitienda.pos"
        WOOCOMMERCE_URL: "https://tu-tienda.com"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: 🔧 Crear proyecto Flutter completo
        script: |
          # Crear proyecto temporal para obtener estructura
          cd /tmp
          flutter create temp_project --platforms=android,windows
          
          # Copiar estructura android al proyecto
          cp -r temp_project/android $CM_BUILD_DIR/
          cp -r temp_project/windows $CM_BUILD_DIR/
          
          # Limpiar
          rm -rf temp_project
          
      - name: 📝 Configurar Android
        script: |
          # Actualizar package name en Android
          sed -i 's/com.example.temp_project/com.mitienda.pos/g' $CM_BUILD_DIR/android/app/build.gradle
          sed -i 's/com.example.temp_project/com.mitienda.pos/g' $CM_BUILD_DIR/android/app/src/main/AndroidManifest.xml
          
          # Crear local.properties
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: 📦 Instalar dependencias
        script: |
          flutter packages pub get
          
      - name: 🔍 Verificar proyecto
        script: |
          flutter doctor -v
          ls -la android/
          
      - name: 🏗️ Build APK
        script: |
          flutter build apk --release --verbose
          
      - name: 🏗️ Build Windows (opcional)
        script: |
          flutter build windows --release --verbose
        ignore_failure: true
        
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - build/windows/runner/Release/
      
    publishing:
      email:
        recipients:
          - tu-email@ejemplo.com
        notify:
          success: true
          failure: false
